<<<<<<< HEAD
spring.application.name=minijira

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
=======


# spring.application.name=minijira

# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}


# spring.jpa.hibernate.ddl-auto=validate
# spring.flyway.enabled=true
# spring.flyway.baseline-on-migrate=true
# # multipart file upload settings
# spring.servlet.multipart.max-file-size=5MB
# spring.servlet.multipart.max-request-size=50MB

# # mailtrap configuration
# # 0ad93a775af6a70d5913922b7276442b
# spring.mail.host=${MAIL_HOST}
# spring.mail.port=${MAIL_PORT}
# spring.mail.username=${MAIL_USERNAME}
# spring.mail.password=${MAIL_PASSWORD}

# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true


# jwt.secret=${JWT_SECRET}
# jwt.expiration=${JWT_EXPIRATION}
>>>>>>> cb67551 ( Reduced to execution time for /project/create api and implemented aop on loggers)
